CREATE TABLE [dbo].[Person](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[address] VARCHAR(100) NOT NULL,
	[first_name] VARCHAR(50) NOT NULL,
	[gender] CHAR(1) NOT NULL,
	[last_name] VARCHAR(80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[person]  WITH CHECK ADD CHECK  (([gender]='F' OR [gender]='M'))
GO